COPY actor FROM 'path/actor_table' DELIMITER ',';
COPY director FROM 'path/director' DELIMITER ',';
COPY genres FROM 'path/genres' DELIMITER ',';
COPY movie FROM 'path/movie' DELIMITER ',';
COPY movie_cast FROM 'path/movie_cast' DELIMITER ',';
COPY movie_direction FROM 'path/movie_direction' DELIMITER ',';
COPY movie_genres FROM 'path/movie_genres' DELIMITER ',';
COPY reviewer FROM 'path/reviewer' DELIMITER ',';
COPY rating FROM 'path/rating' DELIMITER ',';
